Fix typo in example
cloudposse/terraform-aws-api-gateway pull request #19
Opened 2022-08-03 20:50 UTC by vanastassiou

## what
* Fixes typo in example module syntax

## why
* Consistent spelling is good

## references
* n/a

2022-08-30 05:36 UTC, vanastassiou commented
@dotCipher @RothAndrew -- any thoughts on this one?

2022-08-30 15:38 UTC, RothAndrew requested changes

2022-08-30 15:38 UTC, RothAndrew commented on README.md
> -  source  = "cloudposse/api-gateway/aws//modules/account-settings"
The double slashes need to stay since it is a subpath

https://www.terraform.io/language/modules/sources#modules-in-package-sub-directories

2022-08-30 16:33 UTC, vanastassiou commented on README.md
> -  source  = "cloudposse/api-gateway/aws//modules/account-settings"
Thanks @RothAndrew, I've fixed that and updated the branch.

2022-08-30 16:36 UTC, RothAndrew approved these changes

2022-08-30 16:36 UTC, RothAndrew commented
/test all

2022-08-30 17:31 UTC, RothAndrew commented
derp. guess I'm not a codeowner. Summoning @cloudposse/engineering or @cloudposse/approvers

2023-01-17 19:57 UTC, vanastassiou commented
Just getting back to this one since I see it still open... @RothAndrew I'm not sure your tag worked, unfortunately.

2023-08-28 23:24 UTC, jamengual approved these changes

2023-08-28 23:25 UTC, jamengual commented
/tests all

2023-08-30 05:11 UTC, vanastassiou commented
@jamengual any idea what has that last test taking so long? I wonder if it's reasonable to skip certain tests if only Markdown files are updated...

2023-08-30 05:15 UTC, jamengual commented
could you run `precommit/terraform` and commit all changes?
then I believe we will need Code owners review from someone in CloudPosse @max-lobur

2023-08-31 16:02 UTC, jamengual commented
/terratest

2023-09-04 14:08 UTC, max-lobur approved these changes

2023-09-04 14:08 UTC, max-lobur commented
/terratest

2023-09-05 13:34 UTC, merged