feat: extend retention period for API Gateway logs
cloudposse/terraform-aws-api-gateway pull request #49
Opened 2024-08-27 19:28 UTC by HectorQuiroz

## what

This feature allows users to customize the retention period of the logs in CloudWatch. 

## why
This is useful for users who need to keep logs for longer periods of time for auditing or compliance purposes.

## references
https://github.com/cloudposse/terraform-aws-api-gateway/issues/48

2024-09-10 19:14 UTC, RoseSecurity requested changes
Is there any way you could run the following to update the docs?

```sh
make init
make readme
```

2024-09-12 22:19 UTC, RoseSecurity commented
And also add a type? I believe this is an `int` and not a `string`

2024-09-23 21:00 UTC, HectorQuiroz commented
> And also add a type? I believe this is an `int` and not a `string`

Hello @RoseSecurity ,

The module documentation says that this variable is a string

<img width="933" alt="image" src="https://github.com/user-attachments/assets/41eaa9d2-22d8-4ca4-9def-cb19529afe47">

Repository: https://github.com/cloudposse/terraform-aws-cloudwatch-logs
Variable: line 12 -15  https://github.com/cloudposse/terraform-aws-cloudwatch-logs/blob/main/variables.tf

2024-09-23 21:06 UTC, jamengual approved these changes
LGTM thanks @HectorQuiroz

2024-09-23 21:07 UTC, HectorQuiroz commented
> Is there any way you could run the following to update the docs?
> 
> ```shell
> make init
> make readme
> ```

hey @RoseSecurity ,

I ran `make init` & `make readme` to update the documentation. 🚀

2024-09-23 21:16 UTC, HectorQuiroz commented
> LGTM thanks @HectorQuiroz

Thanks @jamengual, I've set the type to be a `string` as required by tf lint. Can you please approve it again? 💯

2024-10-30 15:05 UTC, HectorQuiroz commented
> > And also add a type? I believe this is an `int` and not a `string`
> 
> Hello @RoseSecurity ,
> 
> The module documentation says that this variable is a string
> 
> <img alt="image" width="933" src="https://private-user-images.githubusercontent.com/83728122/370047678-41eaa9d2-22d8-4ca4-9def-cb19529afe47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDA4MzcsIm5iZiI6MTczMDMwMDUzNywicGF0aCI6Ii84MzcyODEyMi8zNzAwNDc2NzgtNDFlYWE5ZDItMjJkOC00Y2E0LTlkZWYtY2IxOTUyOWFmZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE1MDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMGU3ZTY3OGQzMjY2OThlYjc0ZWU0OTQwNDE1NmE1NzIwODI2YzFhMTgzNWM5NGMwMjUxNWY1YjU3MzI5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sUY-pM8W9Ud9TLEFYtFVQorKOJ9qeF0Cip5dFB7gHXo">
> Repository: https://github.com/cloudposse/terraform-aws-cloudwatch-logs Variable: line 12 -15 https://github.com/cloudposse/terraform-aws-cloudwatch-logs/blob/main/variables.tf

2025-02-19 18:53 UTC, closed without merging